
#
# Install the JCE files
# Unzips on the Ansible localhost machine
# 

- name: download jce
  get_url:
    url:     "{{ jce_versions[java_version[0:1]].jce_download_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ jce_local_zip }}"
  when: "{{ java_download_from_oracle }}"
  run_once: true
  delegate_to: 127.0.0.1
 
- name: remove temp folder
  file: path={{ jce_local_dir }} state=absent
  run_once: true
  delegate_to: 127.0.0.1

- name: create temp folder
  file: path={{ jce_local_dir }} state=directory
  run_once: true
  delegate_to: 127.0.0.1

- name: unzip the policy file.
  unarchive:
    src: "{{ jce_local_zip }}"
    dest: "{{ jce_local_dir }}"
    copy: no
  run_once: true
  delegate_to: 127.0.0.1

- name: copy over files
  copy: 
    src="{{ jce_local_dir }}/{{ jce_artifact_base }}/{{ item }}" 
    dest="{{ java_real_home }}/jre/lib/security/{{ item }}" 
    mode=0644
  with_items:
    - local_policy.jar
    - US_export_policy.jar

- name: remove temp folder
  file: path="{{ jce_local_dir }}" state=absent
  run_once: true
  delegate_to: 127.0.0.1

- name: remove zip file
  file: path="{{ jce_local_zip }}" state=absent
  run_once: true
  delegate_to: 127.0.0.1

- name: Configure Java to use /dev/urandom. 
  lineinfile:
    dest="{{ java_real_home }}/jre/lib/security/java.security"
    regexp="^securerandom.source="
    line="securerandom.source=file:/dev/./urandom"
  when: "{{ java_entropy_fix }}"
